server.port=8080
spring.application.name=aqi-data-service
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] [rid=%X{requestId}] %-5level %logger{36} - %msg%n
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=aqi-data-service
info.app.description=AQI data fetching and BigQuery service
